name: KiloDungeons
version: "0.2"
authors:
  - IPat
  - WolfHybrid23

api-version: "1.13"
load: STARTUP

main: me.phein.kiloplugins.mc.kilodungeons.KiloDungeonsPlugin

commands:
  kilodungeons:
    aliases: [kdungeons, kdun, kd]
    description: Provides general information about the plugin.
    permission: kilo.dungeons.info
  dungeonnotify:
    aliases: [kdunnotify, kdnotify, kdunalert, kdalert]
    description: Notifies you if a dungeon gets generated.
    permission: kilo.dungeons.notify
  dungeongenerate:
    aliases: [dungen, kdungen, kdgen]
    description: Generates a dungeon.
    permission: kilo.dungeons.generate

permissions:
  kilo.*:
    description: Universal Kilo plugin permission
    default: op
    children:
      - kilo.dungeons.*
  kilo.dungeons.*:
    description: Universal KiloDungeons plugin permission
    default: op
    children:
      - kilo.dungeons.info
      - kilo.dungeons.notify
      - kilo.dungeons.generate

  kilo.dungeons.info:
    description: Permission to get general information about the plugin
    default: op
  kilo.dungeons.notify:
    description: Permission to get notified when a dungeon gets generated.
    default: op
  kilo.dungeons.generate:
    description: Permission to generate dungeons anywhere.
    default: op